### ISSUE TITLE
Cannot open an issue on /EOSIO/eosjs

### ISSUE THREAD

**Issue by louismerlin** [eosjs/eosjs#2]
As https://github.com/EOSIO/eosjs is a fork of this repo, I cannot open an issue on it.
A solution would be to definitely move this repo onto EOSIO.
The reason why I wanted to open an issue is to ask whether you needed any help with this library ? I would be open to help :smile:

**Comment by louismerlin** [comment]
Or mabye to eosjs-ui ? I have some React experience

**Comment by jcalfee** [comment]
Thanks .. the issues are available now in the eosio repository.  I linked to your post above in our chat too..
